name: openingsource_daily
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^2.1.0
  fluttertoast: ^3.0.3
  http: ^0.12.0+2
  html2md: ^0.3.1
  flutter_markdown: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
  - family: iconfont
    fonts:
      - asset: assets/fonts/iconfont.ttf
  - family: Comfortaa-Bold
    fonts:
      - asset: assets/fonts/Comfortaa-Bold.ttf
  - family: Comfortaa-Light
    fonts:
      - asset: assets/fonts/Comfortaa-Light.ttf
  - family: Comfortaa-Regular
    fonts:
      - asset: assets/fonts/Comfortaa-Regular.ttf
